"""Tests for markdown_utils: formatting, source extraction, HTML conversion."""

import pytest
from app.utils.markdown_utils import (
    extract_sources_from_report,
    format_report,
    report_to_html,
)


class TestFormatReport:
    """Tests for format_report()."""

    def test_basic_formatting(self):
        """Should wrap content with a title header and metadata."""
        result = format_report("Test Task", "## Findings\n\nSome content.")
        assert result.startswith("# Research Report: Test Task")
        assert "> **Generated by DeepResearch-Agent**" in result
        assert "## Findings" in result
        assert "Some content." in result

    def test_with_sources(self):
        """Should append a references section when sources are provided."""
        sources = [
            {"title": "Source One", "url": "https://example.com/1"},
            {"title": "Source Two", "url": "https://example.com/2"},
        ]
        result = format_report("Test", "## Body\n\nContent", sources=sources)
        assert "## References" in result
        assert "Source One" in result
        assert "https://example.com/1" in result
        assert "Source Two" in result

    def test_empty_content_gets_abstract(self):
        """Content without a heading should get '## Abstract' prepended."""
        result = format_report("Test", "Just some plain text.")
        assert "## Abstract" in result
        assert "Just some plain text." in result

    def test_without_sources(self):
        """When sources is None, no references section should appear."""
        result = format_report("Test", "## Body\n\nContent")
        assert "## References" not in result

    def test_empty_sources_list(self):
        """An empty sources list should not produce a references section."""
        result = format_report("Test", "## Body\n\nContent", sources=[])
        assert "## References" not in result


class TestExtractSourcesFromReport:
    """Tests for extract_sources_from_report()."""

    def test_extracts_markdown_links(self):
        """Should extract URLs from [text](url) patterns."""
        report = "See [OpenAI](https://openai.com) and [Google](https://google.com)."
        sources = extract_sources_from_report(report)
        assert "https://openai.com" in sources
        assert "https://google.com" in sources

    def test_extracts_bare_urls(self):
        """Should extract bare http/https URLs."""
        report = "Visit https://example.com for more info."
        sources = extract_sources_from_report(report)
        assert "https://example.com" in sources

    def test_deduplicates_urls(self):
        """Duplicate URLs should only appear once."""
        report = "[A](https://x.com) and [B](https://x.com)"
        sources = extract_sources_from_report(report)
        assert len(sources) == 1

    def test_empty_report_returns_empty_list(self):
        """An empty report should return an empty list."""
        assert extract_sources_from_report("") == []

    def test_no_urls_returns_empty_list(self):
        """A report with no URLs should return an empty list."""
        assert extract_sources_from_report("Just plain text.") == []


class TestReportToHtml:
    """Tests for report_to_html()."""

    def test_headings(self):
        """Should convert # headings to <h1>, <h2>, etc."""
        html = report_to_html("# Title\n## Section\n### Sub")
        assert "<h1>Title</h1>" in html
        assert "<h2>Section</h2>" in html
        assert "<h3>Sub</h3>" in html

    def test_bold_and_italic(self):
        """Should convert **bold** and *italic*."""
        html = report_to_html("**bold** and *italic*")
        assert "<strong>bold</strong>" in html
        assert "<em>italic</em>" in html

    def test_code_blocks(self):
        """Should convert ```code``` blocks to <pre><code>."""
        md = "```\nprint('hello')\n```"
        html = report_to_html(md)
        assert "<pre><code>" in html
        assert "print('hello')" in html
        assert "</code></pre>" in html

    def test_links(self):
        """Should convert [text](url) to <a>."""
        html = report_to_html("[Click](https://example.com)")
        assert '<a href="https://example.com">Click</a>' in html

    def test_unordered_list(self):
        """Should convert - items to <ul><li>."""
        html = report_to_html("- Item A\n- Item B")
        assert "<ul>" in html
        assert "<li>Item A</li>" in html
        assert "<li>Item B</li>" in html
        assert "</ul>" in html

    def test_ordered_list(self):
        """Should convert 1. items to <ol><li>."""
        html = report_to_html("1. First\n2. Second")
        assert "<ol>" in html
        assert "<li>First</li>" in html
        assert "<li>Second</li>" in html
        assert "</ol>" in html

    def test_blockquote(self):
        """Should convert > quotes to <blockquote>."""
        html = report_to_html("> A wise quote")
        assert "<blockquote>" in html
        assert "A wise quote" in html

    def test_inline_code(self):
        """Should convert `code` to <code>."""
        html = report_to_html("Use `print()` function.")
        assert "<code>print()</code>" in html

    def test_paragraphs(self):
        """Regular text should be wrapped in <p> tags."""
        html = report_to_html("Hello world")
        assert "<p>Hello world</p>" in html

    def test_horizontal_rule(self):
        """--- should become <hr>."""
        html = report_to_html("Above\n\n---\n\nBelow")
        assert "<hr>" in html

    def test_html_escaping_in_code(self):
        """HTML entities in code blocks should be escaped."""
        md = "```\n<div>tag</div>\n```"
        html = report_to_html(md)
        assert "&lt;div&gt;tag&lt;/div&gt;" in html

    def test_empty_string(self):
        """Empty string should produce empty HTML."""
        assert report_to_html("").strip() == ""
