"""Markdown formatting and conversion utilities for report generation."""

import re
from typing import Dict, List, Optional


def format_report(task: str, report_content: str, sources: Optional[List[Dict[str, str]]] = None) -> str:
    """Format a complete report with proper markdown structure.

    Ensures consistent formatting: headings, lists, code blocks, citations.

    Args:
        task: The original research task/question.
        report_content: The raw report body text.
        sources: Optional list of source dicts with 'url' and 'title' keys.

    Returns:
        A well-formatted markdown report string.
    """
    lines: List[str] = []
    lines.append(f"# Research Report: {task}")
    lines.append("")

    # Add metadata
    lines.append("> **Generated by DeepResearch-Agent**")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Clean and normalize the content
    cleaned = _normalize_content(report_content)

    # Ensure content starts with a proper heading if it doesn't have one
    if not cleaned.startswith("##") and not cleaned.startswith("#"):
        cleaned = "## Abstract\n\n" + cleaned

    lines.append(cleaned)

    # Append sources section
    if sources:
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## References")
        lines.append("")
        for i, src in enumerate(sources, 1):
            title = src.get("title", src.get("url", f"Source {i}"))
            url = src.get("url", "")
            if url:
                lines.append(f"{i}. [{title}]({url})")
            else:
                lines.append(f"{i}. {title}")

    return "\n".join(lines).strip()


def extract_sources_from_report(report: str) -> List[str]:
    """Extract referenced URLs/sources from a report.

    Looks for markdown links [text](url), bare URLs, and numbered
    reference patterns.

    Args:
        report: The markdown report text.

    Returns:
        A list of extracted URL strings.
    """
    sources: List[str] = []
    seen: set = set()

    # Pattern 1: Markdown links [text](url)
    md_links = re.findall(r"\[([^\]]+)\]\(([^)]+)\)", report)
    for text, url in md_links:
        url = url.strip()
        if url and url not in seen:
            seen.add(url)
            sources.append(url)

    # Pattern 2: Bare URLs (http/https)
    bare_urls = re.findall(
        r"(?<!\]\()\bhttps?://[^\s\)\]\"'>]+", report
    )
    for url in bare_urls:
        url = url.rstrip(".,;:!?")
        if url and url not in seen:
            seen.add(url)
            sources.append(url)

    return sources


def report_to_html(report: str) -> str:
    """Convert markdown report to HTML (basic conversion without extra deps).

    Handles: # headings, **bold**, *italic*, - lists, [links](url), ```code blocks```,
    numbered lists, blockquotes, inline code, paragraphs.

    Args:
        report: The markdown report text.

    Returns:
        An HTML string.
    """
    html_parts: List[str] = []
    in_code_block = False
    code_buffer: List[str] = []
    in_list = False
    in_ordered_list = False

    lines = report.split("\n")

    for i, line in enumerate(lines):
        # Code block handling
        if line.strip().startswith("```"):
            if in_code_block:
                # Close code block
                newline = '\n'
                html_parts.append(f"<pre><code>{_escape_html(newline.join(code_buffer))}</code></pre>")
                code_buffer = []
                in_code_block = False
            else:
                in_code_block = True
            continue

        if in_code_block:
            code_buffer.append(line)
            continue

        # Close open list if needed
        if in_list and not line.startswith("- ") and not line.startswith("* ") and not line.strip() == "":
            html_parts.append("</ul>")
            in_list = False
        if in_ordered_list and not re.match(r"^\d+\.\s", line) and not line.strip() == "":
            html_parts.append("</ol>")
            in_ordered_list = False

        # Empty line
        if line.strip() == "":
            if not in_list and not in_ordered_list:
                html_parts.append("")
            continue

        # Headings
        heading_match = re.match(r"^(#{1,6})\s+(.+)$", line)
        if heading_match:
            level = len(heading_match.group(1))
            text = heading_match.group(2)
            html_parts.append(f"<h{level}>{_process_inline(text)}</h{level}>")
            continue

        # Horizontal rule
        if line.strip() == "---":
            html_parts.append("<hr>")
            continue

        # Blockquote
        if line.startswith(">"):
            text = line.lstrip(">").strip()
            html_parts.append(f"<blockquote>{_process_inline(text)}</blockquote>")
            continue

        # Unordered list
        list_match = re.match(r"^[\-\*]\s+(.+)$", line)
        if list_match:
            if not in_list:
                html_parts.append("<ul>")
                in_list = True
            html_parts.append(f"<li>{_process_inline(list_match.group(1))}</li>")
            continue

        # Ordered list
        ol_match = re.match(r"^(\d+)\.\s+(.+)$", line)
        if ol_match:
            if not in_ordered_list:
                html_parts.append("<ol>")
                in_ordered_list = True
            html_parts.append(f"<li>{_process_inline(ol_match.group(2))}</li>")
            continue

        # Regular paragraph
        html_parts.append(f"<p>{_process_inline(line)}</p>")

    # Close any remaining open tags
    if in_code_block:
        newline = '\n'
        html_parts.append(f"<pre><code>{_escape_html(newline.join(code_buffer))}</code></pre>")
    if in_list:
        html_parts.append("</ul>")
    if in_ordered_list:
        html_parts.append("</ol>")

    return "\n".join(html_parts)


def _process_inline(text: str) -> str:
    """Process inline markdown elements within a line of text.

    Handles: **bold**, *italic*, `inline code`, [links](url).
    """
    # Bold (**text**)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Italic (*text*)
    text = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"<em>\1</em>", text)
    # Inline code
    text = re.sub(r"`(.+?)`", lambda m: f"<code>{_escape_html(m.group(1))}</code>", text)
    # Links [text](url)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)

    return text


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _normalize_content(content: str) -> str:
    """Normalize report content: fix spacing, normalize line endings."""
    # Normalize line endings
    content = content.replace("\r\n", "\n").replace("\r", "\n")

    # Remove excessive blank lines (more than 2 consecutive)
    while "\n\n\n" in content:
        content = content.replace("\n\n\n", "\n\n")

    return content.strip()


def _extract_heading(text: str, level: int = 1) -> Optional[str]:
    """Extract the first heading of a given level from text."""
    pattern = r"^" + "#" * level + r"\s+(.+)$"
    match = re.search(pattern, text, re.MULTILINE)
    if match:
        return match.group(1).strip()
    return None
